#!/bin/bash
# Outer orchestration loop for `elfuzz direct` mode.
#
# Sibling of all_gen.sh. Differences:
#  - The initial seed corpus is generated by an LLM (no .py seed file is copied).
#  - Each per-generation step calls do_gen_direct.sh, which works on directories
#    of inputs (collections) instead of Python fuzzer programs.

set -euo pipefail

if [ "$#" -eq 1 ]; then
    start_gen=-1
elif [ "$#" -eq 2 ]; then
    start_gen=$2
else
    echo "Usage: $0 rundir [start_gen]"
    exit 1
fi

# elmconfig.py needs $ELMFUZZ_RUNDIR to find the per-benchmark config.yaml.
export ELMFUZZ_RUNDIR="$1"
export ELMFUZZ_RUN_NAME=$(basename "$ELMFUZZ_RUNDIR")

if [ -n "${NUM_GENERATIONS:-}" ]; then
    num_gens=${NUM_GENERATIONS}
else
    num_gens=$(./elmconfig.py get run.num_generations)
fi
last_gen=$((num_gens - 1))

genout_dir=$(./elmconfig.py get run.genoutput_dir -s GEN=. -s MODEL=.)
export ENDPOINTS=$(./elmconfig.py get model.endpoints)
export TYPE=$(./elmconfig.py get type)
export PROJECT_NAME=$(./elmconfig.py get project_name)
genout_dir=$(realpath -m "$genout_dir")

LLM_BACKEND="${ELMFUZZ_LLM_BACKEND:-huggingface}"

NUM_INITIAL_COLLECTIONS=${ELFUZZ_DIRECT_NUM_INITIAL_COLLECTIONS:-20}
INPUTS_PER_COLLECTION=${ELFUZZ_DIRECT_INPUTS_PER_COLLECTION:-50}
INPUT_EXTENSION=${ELFUZZ_DIRECT_INPUT_EXTENSION:-.bin}
HF_INITIAL_PREFIX=${ELFUZZ_DIRECT_HF_INITIAL_PREFIX:-}
FMT_NAME=${ELFUZZ_DIRECT_FORMAT_NAME:-text}
FMT_DESC=${ELFUZZ_DIRECT_FORMAT_DESCRIPTION:-text input}

# Resolve the LLM model name + endpoint same way do_gen_direct.sh does.
if [ "$LLM_BACKEND" = "copilot" ]; then
    LLM_MODEL_NAME="${ELMFUZZ_COPILOT_MODEL:-gpt-4.1}"
    INITIAL_ENDPOINT_ARGS=()
else
    LLM_MODEL_NAME="${ELFUZZ_DIRECT_HF_MODEL_OVERRIDE:-$(./elmconfig.py get model.names | awk '{print $1}')}"
    LLM_ENDPOINT=""
    for pair in $ENDPOINTS ; do
        name=${pair%%:*}
        url=${pair#*:}
        if [ "$name" = "$LLM_MODEL_NAME" ]; then
            LLM_ENDPOINT="$url"
            break
        fi
    done
    if [ -z "$LLM_ENDPOINT" ]; then
        first_pair=$(echo "$ENDPOINTS" | awk '{print $1}')
        LLM_ENDPOINT=${first_pair#*:}
    fi
    INITIAL_ENDPOINT_ARGS=(-E "$LLM_ENDPOINT")
fi

should_clean=$(./elmconfig.py get run.clean)
if [ -d "$genout_dir" ]; then
    if [ "$should_clean" = "True" ]; then
        echo "Removing generated outputs in $genout_dir"
        rm -rf "$genout_dir"
    else
        echo "Generated output directory $genout_dir already exists; exiting."
        echo "Set run.clean to True to remove existing rundirs."
        exit 1
    fi
fi
if [ "$start_gen" -eq -1 ]; then
    for pat in "gen*" "initial" "stamps"; do
        if compgen -G "$ELMFUZZ_RUNDIR"/$pat > /dev/null; then
            if [ "$should_clean" = "True" ]; then
                echo "Removing existing rundir(s):" "$ELMFUZZ_RUNDIR"/$pat
                rm -rf "$ELMFUZZ_RUNDIR"/$pat
            else
                echo "Found existing rundir(s):" "$ELMFUZZ_RUNDIR"/$pat
                echo "Set run.clean to True to remove existing rundirs."
                exit 1
            fi
        fi
    done
fi

if [ "$TYPE" = "fuzzbench" ]; then
    python prepare_fuzzbench.py
elif [ "$TYPE" = "oss-fuzz" ]; then
    python prepare_fuzzbench.py -d /home/appuser/oss-fuzz -t oss-fuzz
elif [ "$TYPE" = "docker" ]; then
    python prepare_fuzzbench.py -t docker
fi

_run_gen() {
    local prev="$1" next="$2" gen_num="$3"
    local t_start
    t_start=$(date +%s)
    echo "================================================================"
    echo "[all_gen_direct] Generation $gen_num / $num_gens  ($prev -> $next)  started at $(date '+%H:%M:%S')"
    echo "================================================================"
    ./do_gen_direct.sh "$prev" "$next"
    local t_end elapsed
    t_end=$(date +%s)
    elapsed=$(( t_end - t_start ))
    echo "[all_gen_direct] Generation $gen_num / $num_gens  done in ${elapsed}s"
}

if [ "$start_gen" -eq -1 ]; then
    mkdir -p "$ELMFUZZ_RUNDIR/initial/seeds"
    mkdir -p "$ELMFUZZ_RUNDIR/stamps"

    echo "===================================================================="
    echo "Generating initial seed corpus via LLM ($LLM_BACKEND, $LLM_MODEL_NAME)"
    echo "  $NUM_INITIAL_COLLECTIONS collections x $INPUTS_PER_COLLECTION inputs"
    echo "===================================================================="
    t_init=$(date +%s)

    python direct_initial.py \
        --rundir "$ELMFUZZ_RUNDIR" \
        --backend "$LLM_BACKEND" \
        -M "$LLM_MODEL_NAME" \
        "${INITIAL_ENDPOINT_ARGS[@]}" \
        --num-collections "$NUM_INITIAL_COLLECTIONS" \
        --inputs-per-collection "$INPUTS_PER_COLLECTION" \
        --input-extension "$INPUT_EXTENSION" \
        --format-name "$FMT_NAME" \
        --format-description "$FMT_DESC" \
        --hf-initial-prefix "$HF_INITIAL_PREFIX"

    echo "[all_gen_direct] Initial corpus done in $(( $(date +%s) - t_init ))s"

    _run_gen initial gen0 0
    for i in $(seq 0 $last_gen); do
        _run_gen "gen$i" "gen$((i+1))" "$((i+1))"
    done
else
    if [ "$start_gen" -eq 0 ]; then
        real_start_gen=0
        _run_gen initial gen0 0
    else
        real_start_gen=$((start_gen-1))
    fi
    for i in $(seq $real_start_gen $last_gen); do
        _run_gen "gen$i" "gen$((i+1))" "$((i+1))"
    done
fi
