"""elfuzz reset — delete all local run artifacts without touching downloaded data."""

from __future__ import annotations

import glob
import os
import shutil
import subprocess

from common import PROJECT_ROOT

BENCHMARKS = ["jsoncpp", "libxml2", "re2", "librsvg", "cvc5", "sqlite3", "cpython3"]

# AFL result tarballs that are from `elfuzz download` and must be preserved.
_RQ1_DOWNLOADED = {"afl_cov_exp.tar.zst"}
_RQ2_DOWNLOADED = {"afl_bug_exp.tar.zst", "triage.tar.zst"}


def _collect_targets() -> list[tuple[str, str]]:
    """Return a list of (description, path) pairs for everything that will be removed."""
    targets: list[tuple[str, str]] = []

    # ---- 1. Evolution run dirs inside preset/ --------------------------------
    for benchmark in BENCHMARKS:
        preset = os.path.join(PROJECT_ROOT, "preset", benchmark)
        for pattern in ("gen*", "initial", "stamps", "pool"):
            for path in sorted(glob.glob(os.path.join(preset, pattern))):
                if os.path.exists(path):
                    targets.append((f"preset/{benchmark} run data", path))

    # ---- 2. Analysis result spreadsheets ------------------------------------
    for rq in ("rq1", "rq2", "rq3"):
        results_dir = os.path.join(PROJECT_ROOT, "analysis", rq, "results")
        for ext in ("*.xlsx", "*.csv"):
            for path in sorted(glob.glob(os.path.join(results_dir, ext))):
                if os.path.isfile(path):
                    targets.append((f"analysis/{rq} results", path))

    # Only generated by `elfuzz plot`; the downloaded copy is `record.csv`.
    x_record = os.path.join(PROJECT_ROOT, "analysis", "timecost", "x_record_second.csv")
    if os.path.isfile(x_record):
        targets.append(("analysis/timecost generated", x_record))

    # ---- 3. Plot outputs ----------------------------------------------------
    plot_dir = os.path.join(PROJECT_ROOT, "plot")
    for subdir in ("fig", "table", "data"):
        d = os.path.join(plot_dir, subdir)
        if not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.startswith("."):
                continue  # skip .gitkeep and other dot-files
            path = os.path.join(d, name)
            targets.append((f"plot/{subdir}", path))

    # ---- 4. Locally-generated AFL result tarballs ---------------------------
    rq1_afl = os.path.join(PROJECT_ROOT, "extradata", "rq1", "afl_results")
    if os.path.isdir(rq1_afl):
        for name in sorted(os.listdir(rq1_afl)):
            if name not in _RQ1_DOWNLOADED:
                targets.append(("extradata/rq1 local AFL results", os.path.join(rq1_afl, name)))

    rq2_afl = os.path.join(PROJECT_ROOT, "extradata", "rq2", "afl_results")
    if os.path.isdir(rq2_afl):
        for name in sorted(os.listdir(rq2_afl)):
            if name not in _RQ2_DOWNLOADED:
                targets.append(("extradata/rq2 local AFL results", os.path.join(rq2_afl, name)))

    return targets


def _remove(path: str) -> None:
    # Runs always use `sudo`, so generated files may be root-owned.
    # Try unprivileged removal first; fall back to `sudo rm -rf`.
    try:
        if os.path.isdir(path):
            shutil.rmtree(path)
        elif os.path.isfile(path):
            os.remove(path)
    except PermissionError:
        subprocess.run(["sudo", "rm", "-rf", path], check=True)


def reset(dry_run: bool = False) -> None:
    targets = _collect_targets()
    if not targets:
        print("Nothing to reset — no local run artifacts found.")
        return

    # Group and print by category for readability.
    by_category: dict[str, list[str]] = {}
    for cat, path in targets:
        by_category.setdefault(cat, []).append(path)

    print("The following run artifacts will be permanently deleted:\n")
    for cat, paths in by_category.items():
        print(f"  [{cat}]")
        for p in paths:
            rel = os.path.relpath(p, PROJECT_ROOT)
            print(f"    {rel}")
    print(f"\nTotal: {len(targets)} item(s).")

    if dry_run:
        print("\n[dry-run] Nothing deleted.")
        return

    for _, path in targets:
        _remove(path)

    print(f"\nReset complete. {len(targets)} item(s) removed.")
    print("To restore downloaded data, run:  elfuzz download --only-relocate")
